/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.Bairro_Controller;
import controller.Cidade_Controller;
import java.awt.Cursor;
import java.util.Iterator;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.beans.Bairro;
import model.beans.Cidade;
import servicos.Maiusculas;

/**
 *
 * @author Gysa
 */
public final class TelaAdmBairro extends javax.swing.JInternalFrame {
    int cod_cidade;
    String nm_cidade;
    /**
     * Creates new form TelaBairro
     */
    public TelaAdmBairro() {
        initComponents();
        jt_pesquisar.setDocument(new Maiusculas());
        preencherCombos();
        jt_pesquisar.requestFocus();
       
        pesquisaBairro("");
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupo = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jt_pesquisar = new javax.swing.JTextField();
        jb_pesquisar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        combo_dados = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jb_atualizar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jb_novo = new javax.swing.JButton();
        jb_alterar = new javax.swing.JButton();
        jb_excluir = new javax.swing.JButton();
        jb_cancelar = new javax.swing.JButton();

        setResizable(true);
        setTitle("Bairros");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jt_pesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jt_pesquisarKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jt_pesquisarKeyReleased(evt);
            }
        });

        jb_pesquisar.setText("Pesquisar");
        jb_pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_pesquisarActionPerformed(evt);
            }
        });

        jLabel1.setText("Cidade:");

        combo_dados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_dadosActionPerformed(evt);
            }
        });

        jLabel2.setText("Área de pesquisa");

        jb_atualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/atualizar.gif"))); // NOI18N
        jb_atualizar.setToolTipText("Atualizar lista de estados");
        jb_atualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_atualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(combo_dados, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jt_pesquisar))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jb_pesquisar)
                            .addComponent(jb_atualizar)))
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jb_atualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(combo_dados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jt_pesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_pesquisar))
                .addContainerGap())
        );

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Bairro", "Cidade"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabela);
        if (tabela.getColumnModel().getColumnCount() > 0) {
            tabela.getColumnModel().getColumn(0).setMinWidth(50);
            tabela.getColumnModel().getColumn(0).setPreferredWidth(50);
            tabela.getColumnModel().getColumn(0).setMaxWidth(60);
            tabela.getColumnModel().getColumn(1).setMinWidth(150);
            tabela.getColumnModel().getColumn(1).setPreferredWidth(150);
            tabela.getColumnModel().getColumn(1).setMaxWidth(250);
        }

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jb_novo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jb_novo.setText("Novo");
        jb_novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_novoActionPerformed(evt);
            }
        });

        jb_alterar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jb_alterar.setText("Alterar");
        jb_alterar.setEnabled(false);
        jb_alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_alterarActionPerformed(evt);
            }
        });

        jb_excluir.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jb_excluir.setText("Excluir");
        jb_excluir.setEnabled(false);
        jb_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_excluirActionPerformed(evt);
            }
        });

        jb_cancelar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jb_cancelar.setText("Cancelar");
        jb_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_cancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jb_novo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jb_alterar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jb_excluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jb_cancelar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_novo)
                    .addComponent(jb_alterar)
                    .addComponent(jb_excluir)
                    .addComponent(jb_cancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_cancelarActionPerformed
        dispose();
    }//GEN-LAST:event_jb_cancelarActionPerformed

    private void jb_pesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_pesquisarActionPerformed
      
        int cd_cidade = 0;
        try{
        Cidade cidade = (Cidade) combo_dados.getSelectedItem();
        cd_cidade = cidade.getCidade_Codigo();
        }catch(Exception e){}
        if(cd_cidade > 0){
            pesquisaBairro(jt_pesquisar.getText(), cd_cidade);
        }else{
            pesquisaBairro(jt_pesquisar.getText());
        }
        
        ativaDesativa(0);
    }//GEN-LAST:event_jb_pesquisarActionPerformed

    private void jb_novoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_novoActionPerformed
        combo_dados.setSelectedIndex(0);
        cadastro(0);
    }//GEN-LAST:event_jb_novoActionPerformed

    private void jb_alterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_alterarActionPerformed
        cadastro(Integer.parseInt(tabela.getValueAt(tabela.getSelectedRow(), 0).toString()));
        combo_dados.setSelectedIndex(0);
        ativaDesativa(0);
        
    }//GEN-LAST:event_jb_alterarActionPerformed

    private void tabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaMouseClicked
        ativaDesativa(1);
    }//GEN-LAST:event_tabelaMouseClicked

    private void jt_pesquisarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jt_pesquisarKeyReleased
        ativaDesativa(0);
    }//GEN-LAST:event_jt_pesquisarKeyReleased

    private void jb_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_excluirActionPerformed
        opcaoExcluir();
        combo_dados.setSelectedIndex(0);
        
    }//GEN-LAST:event_jb_excluirActionPerformed

    private void jt_pesquisarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jt_pesquisarKeyPressed
      if(evt.getKeyCode() == 10){
           jb_pesquisar.doClick();
           
        }
    }//GEN-LAST:event_jt_pesquisarKeyPressed

    private void combo_dadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_dadosActionPerformed
        jb_pesquisar.doClick();
    }//GEN-LAST:event_combo_dadosActionPerformed

    private void jb_atualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_atualizarActionPerformed
      preencherCombos();
    }//GEN-LAST:event_jb_atualizarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox combo_dados;
    private javax.swing.ButtonGroup grupo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jb_alterar;
    private javax.swing.JButton jb_atualizar;
    private javax.swing.JButton jb_cancelar;
    private javax.swing.JButton jb_excluir;
    private javax.swing.JButton jb_novo;
    private javax.swing.JButton jb_pesquisar;
    private javax.swing.JTextField jt_pesquisar;
    private static javax.swing.JTable tabela;
    // End of variables declaration//GEN-END:variables
    static Bairro bairro;
    static Bairro_Controller bairro_Controller;
    static List lista;
    static Iterator iterator;
    
    
    public static void pesquisaBairro(String texto){
        Cursor.getPredefinedCursor(3);
        bairro_Controller = new Bairro_Controller();
        lista = bairro_Controller.getBairroList(texto);
        preencherTabela();
        Cursor.getDefaultCursor();
    }
    
    public static void pesquisaBairro(String texto, int cidade){
        Cursor.getPredefinedCursor(3);
        bairro_Controller = new Bairro_Controller();
        lista = bairro_Controller.getBairroList(texto, cidade);
        preencherTabela();
        Cursor.getDefaultCursor();
    }
    
  
    
    private static void preencherTabela(){
        DefaultTableModel linha = (DefaultTableModel) tabela.getModel();
        linha.setNumRows(0);
        iterator = lista.iterator();
        while(iterator.hasNext()){
            bairro = (Bairro) iterator.next();
            linha.addRow(new Object[]{
               bairro.getCd_bairro(),
               bairro.getNm_bairro(),
               bairro.getCidade_Descricao()
               
            });
        }
    }
  private void cadastro(int codigo){
      
      TelaCadBairro tela = new TelaCadBairro(codigo);
      TelaPrincipal.desktop.add(tela);
      tela.show();
  }
  
  private void ativaDesativa(int op){
      if(op == 0){
          jb_alterar.setEnabled(false);
          jb_excluir.setEnabled(false);
      }
      else{
          jb_alterar.setEnabled(true);
          jb_excluir.setEnabled(true);
      }
  }
  
  private void excluir(){
      bairro_Controller =  new Bairro_Controller();
//      System.out.println("Codigo para excluir: "+tabela.getValueAt(tabela.getSelectedRow(), 0));
      boolean teste = bairro_Controller.excluir(
              Integer.parseInt(tabela.getValueAt(tabela.getSelectedRow(), 0).toString()));
      if(teste){
          pesquisaBairro("");
          mensagem("Item removido com sucesso!", "Muito bem!", JOptionPane.INFORMATION_MESSAGE);
          ativaDesativa(0);
      }
      else{
          mensagem("Um ocorreu, possivelmente existe cadastro associado a este item", "Erro", JOptionPane.ERROR_MESSAGE);
          ativaDesativa(0);
      }
  }
  
  private void mensagem(String mensagem, String titulo, int tipo){
      JOptionPane.showMessageDialog(null, mensagem, titulo, tipo);
  }
  private int mensagem1(String mensagem, String titulo, int tipo ){
      int op = JOptionPane.showConfirmDialog(null, mensagem, titulo,  JOptionPane.YES_NO_OPTION, tipo);
      return op;
  }
  
  private void opcaoExcluir(){
      int op = mensagem1("Tem certeza que deseja excluir?", "Confirmação", JOptionPane.QUESTION_MESSAGE);
      if(op == JOptionPane.YES_OPTION){
          excluir();
      }
  }
  
  public void preencherCombos(){
      combo_dados.removeAllItems();
      Cidade_Controller ec = new Cidade_Controller();
      Cidade cidade;
      
      List lista1 = ec.getCidadeList("");
      Iterator iterator1 = lista1.iterator();
      combo_dados.addItem("SELECIONE");
      while(iterator1.hasNext()){
          cidade = (Cidade) iterator1.next();
          combo_dados.addItem(cidade);
      }
      
  }
  
  
}//fim do arquivo
