/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Cursor;
import javax.swing.JInternalFrame;

/**
 *
 * @author Gysa
 */
public class TelaPrincipal extends javax.swing.JFrame {
     String titulo = "Sistema Gerenciamento de Clube - SGC";
    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        setTitle(titulo);
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktop = new javax.swing.JDesktopPane();
        jMenuBarra = new javax.swing.JMenuBar();
        jMenuArquivo = new javax.swing.JMenu();
        jMenuCadastros = new javax.swing.JMenu();
        jMenuAno = new javax.swing.JMenuItem();
        jMenuDivisao = new javax.swing.JMenuItem();
        jMenuUniao = new javax.swing.JMenuItem();
        jMenuAssociacao = new javax.swing.JMenuItem();
        jMenuDistrito = new javax.swing.JMenuItem();
        jMenuRegiao = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuTipoDeContato = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuResidencia = new javax.swing.JMenu();
        jMenuPais = new javax.swing.JMenuItem();
        jMenuEstado = new javax.swing.JMenuItem();
        jMenuCidade = new javax.swing.JMenuItem();
        jMenuBairro = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        javax.swing.GroupLayout desktopLayout = new javax.swing.GroupLayout(desktop);
        desktop.setLayout(desktopLayout);
        desktopLayout.setHorizontalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        desktopLayout.setVerticalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        getContentPane().add(desktop);

        jMenuArquivo.setText("Arquivo");
        jMenuBarra.add(jMenuArquivo);

        jMenuCadastros.setText("Cadastros");

        jMenuAno.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        jMenuAno.setText("Ano");
        jMenuAno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAnoActionPerformed(evt);
            }
        });
        jMenuCadastros.add(jMenuAno);

        jMenuDivisao.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.ALT_MASK));
        jMenuDivisao.setText("Divisão");
        jMenuDivisao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuDivisaoActionPerformed(evt);
            }
        });
        jMenuCadastros.add(jMenuDivisao);

        jMenuUniao.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.ALT_MASK));
        jMenuUniao.setText("União");
        jMenuUniao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuUniaoActionPerformed(evt);
            }
        });
        jMenuCadastros.add(jMenuUniao);

        jMenuAssociacao.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK));
        jMenuAssociacao.setText("Associação");
        jMenuAssociacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAssociacaoActionPerformed(evt);
            }
        });
        jMenuCadastros.add(jMenuAssociacao);

        jMenuDistrito.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        jMenuDistrito.setText("Distrito");
        jMenuDistrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuDistritoActionPerformed(evt);
            }
        });
        jMenuCadastros.add(jMenuDistrito);

        jMenuRegiao.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.ALT_MASK));
        jMenuRegiao.setText("Região");
        jMenuRegiao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuRegiaoActionPerformed(evt);
            }
        });
        jMenuCadastros.add(jMenuRegiao);
        jMenuCadastros.add(jSeparator1);

        jMenuTipoDeContato.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
        jMenuTipoDeContato.setText("Tipo de Contato");
        jMenuTipoDeContato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuTipoDeContatoActionPerformed(evt);
            }
        });
        jMenuCadastros.add(jMenuTipoDeContato);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem1.setText("Tipo de Pessoa");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenuCadastros.add(jMenuItem1);
        jMenuCadastros.add(jSeparator2);

        jMenuResidencia.setText("Residencial");

        jMenuPais.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMenuPais.setText("País");
        jMenuPais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuPaisActionPerformed(evt);
            }
        });
        jMenuResidencia.add(jMenuPais);

        jMenuEstado.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        jMenuEstado.setText("Estado");
        jMenuEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuEstadoActionPerformed(evt);
            }
        });
        jMenuResidencia.add(jMenuEstado);

        jMenuCidade.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuCidade.setText("Cidade");
        jMenuCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCidadeActionPerformed(evt);
            }
        });
        jMenuResidencia.add(jMenuCidade);

        jMenuBairro.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        jMenuBairro.setText("Bairro");
        jMenuBairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuBairroActionPerformed(evt);
            }
        });
        jMenuResidencia.add(jMenuBairro);

        jMenuCadastros.add(jMenuResidencia);

        jMenuBarra.add(jMenuCadastros);

        setJMenuBar(jMenuBarra);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuDivisaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuDivisaoActionPerformed
        setCursor(Cursor.getPredefinedCursor(3));
        chamaTela(new TelaAdmDivisao());
        setCursor(Cursor.getPredefinedCursor(0));
    }//GEN-LAST:event_jMenuDivisaoActionPerformed

    private void jMenuUniaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuUniaoActionPerformed
        setCursor(Cursor.getPredefinedCursor(3));
        chamaTela(new TelaAdmUniao());
        setCursor(Cursor.getPredefinedCursor(0));
    }//GEN-LAST:event_jMenuUniaoActionPerformed

    private void jMenuAssociacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAssociacaoActionPerformed
        setCursor(Cursor.getPredefinedCursor(3));
        chamaTela(new TelaAdmAssociacao());
        setCursor(Cursor.getPredefinedCursor(0));
    }//GEN-LAST:event_jMenuAssociacaoActionPerformed

    private void jMenuAnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAnoActionPerformed
        setCursor(Cursor.getPredefinedCursor(3));
        chamaTela(new TelaAdmAno());
        setCursor(Cursor.getPredefinedCursor(0));
    }//GEN-LAST:event_jMenuAnoActionPerformed

    private void jMenuDistritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuDistritoActionPerformed
        setCursor(Cursor.getPredefinedCursor(3));
        chamaTela(new TelaAdmDistrito());
        setCursor(Cursor.getPredefinedCursor(0));
    }//GEN-LAST:event_jMenuDistritoActionPerformed

    private void jMenuRegiaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuRegiaoActionPerformed
        setCursor(Cursor.getPredefinedCursor(3));
        chamaTela(new TelaAdmRegiao());
        setCursor(Cursor.getPredefinedCursor(0));
    }//GEN-LAST:event_jMenuRegiaoActionPerformed

    private void jMenuTipoDeContatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuTipoDeContatoActionPerformed
        setCursor(Cursor.getPredefinedCursor(3));
        chamaTela(new TelaAdmTipo_Contato());
        setCursor(Cursor.getPredefinedCursor(0));
    }//GEN-LAST:event_jMenuTipoDeContatoActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        setCursor(Cursor.getPredefinedCursor(3));
        chamaTela(new TelaAdmTipo_Pessoa());
        setCursor(Cursor.getPredefinedCursor(0));
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuPaisActionPerformed
        setCursor(Cursor.getPredefinedCursor(3));
        chamaTela(new TelaAdmPais());
        setCursor(Cursor.getPredefinedCursor(0));
    }//GEN-LAST:event_jMenuPaisActionPerformed

    private void jMenuEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuEstadoActionPerformed
        setCursor(Cursor.getPredefinedCursor(3));
        chamaTela(new TelaAdmEstado());
        setCursor(Cursor.getPredefinedCursor(0));
    }//GEN-LAST:event_jMenuEstadoActionPerformed

    private void jMenuCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCidadeActionPerformed
        setCursor(Cursor.getPredefinedCursor(3));
        chamaTela(new TelaAdmCidade());
        setCursor(Cursor.getPredefinedCursor(0));
    }//GEN-LAST:event_jMenuCidadeActionPerformed

    private void jMenuBairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuBairroActionPerformed
        setCursor(Cursor.getPredefinedCursor(3));
        chamaTela(new TelaAdmBairro());
        setCursor(Cursor.getPredefinedCursor(0));
    }//GEN-LAST:event_jMenuBairroActionPerformed
private void chamaTela(JInternalFrame tela){
        JInternalFrame screen = tela;
        desktop.add(screen);
        screen.show();
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JDesktopPane desktop;
    private javax.swing.JMenuItem jMenuAno;
    private javax.swing.JMenu jMenuArquivo;
    private javax.swing.JMenuItem jMenuAssociacao;
    private javax.swing.JMenuItem jMenuBairro;
    private javax.swing.JMenuBar jMenuBarra;
    private javax.swing.JMenu jMenuCadastros;
    private javax.swing.JMenuItem jMenuCidade;
    private javax.swing.JMenuItem jMenuDistrito;
    private javax.swing.JMenuItem jMenuDivisao;
    private javax.swing.JMenuItem jMenuEstado;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuPais;
    private javax.swing.JMenuItem jMenuRegiao;
    private javax.swing.JMenu jMenuResidencia;
    private javax.swing.JMenuItem jMenuTipoDeContato;
    private javax.swing.JMenuItem jMenuUniao;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    // End of variables declaration//GEN-END:variables
    
}
